<!-- <section class="area_distribuidor">
	<div class="container">
		<div class="title_2">NOSSOS CLIENTES</div>
		<div class="text_dist">
			Para ser um distribuidor Granipisos, entre em contato conosco, acesse um de nossos canais de comunicação ou pelo nosso ícone do Whatsapp.
		</div>
		<div class="contato_dist">

			<div class="carousel">
				<a class="carousel-item" href="#one!"><img src="<?= base_path(); ?>images/tecnologias/angular.png"></a>
				<a class="carousel-item" href="#one!"><img src="<?= base_path(); ?>images/tecnologias/centos.png"></a>
				<a class="carousel-item" href="#one!"><img src="<?= base_path(); ?>images/tecnologias/css3.png"></a>
				<a class="carousel-item" href="#one!"><img src="<?= base_path(); ?>images/tecnologias/redhat.png"></a>
				<a class="carousel-item" href="#one!"><img src="<?= base_path(); ?>images/tecnologias/debian.png"></a>
				<a class="carousel-item" href="#one!"><img src="<?= base_path(); ?>images/tecnologias/php.png"></a>
			</div>

			<?php if ( ! empty($redes_sociais['whatsapp']) ) : ?>
			<a href="https://wa.me/<?= limpa_string($redes_sociais['whatsapp'], ''); ?>" target="_blank">
				<span class="icon_dist">
					<img src="<?= base_path(true); ?>img/icons/icon_whats_b.png" class="img_cem">
				</span>
			</a>
			<?php endif; ?>

			<a href="<?= ! empty($redes_sociais['email']) ? 'mailto://' . $redes_sociais['email'] : '#'; ?>">
				<span class="icon_dist">
					<img src="<?= base_path(true); ?>img/icons/icon_envelope_b.png" class="img_cem">
				</span>
			</a>

			<a href="<?= $redes_sociais['facebook'] ?? '#'; ?>" target="_blank">
				<span class="icon_dist">
					<img src="<?= base_path(true); ?>img/icons/icon_face_b.png" class="img_cem">
				</span>
			</a>

			<a href="<?= $redes_sociais['instagram'] ?? '#'; ?>" target="_blank">
				<span class="icon_dist">
					<img src="<?= base_path(true); ?>img/icons/icon_insta_b.png" class="img_cem">
				</span>
			</a>

			<div class="test">Click</div>
		</div>

	</div>
</section> -->
